#pragma once

using uint = unsigned int;

#define DECLARE_PROBLEM(num) \
struct Problem##num \
{ \
	static void RunTest(); \
}; 

DECLARE_PROBLEM( 1 );
DECLARE_PROBLEM( 2 );
DECLARE_PROBLEM( 3 );
DECLARE_PROBLEM( 4 );
DECLARE_PROBLEM( 5 );
DECLARE_PROBLEM( 6 );
DECLARE_PROBLEM( 7 );
DECLARE_PROBLEM( 8 );
DECLARE_PROBLEM( 9 );
DECLARE_PROBLEM( 10 );
DECLARE_PROBLEM( 11 );
DECLARE_PROBLEM( 12 );
DECLARE_PROBLEM( 13 );
DECLARE_PROBLEM( 14 );
